In [1]:
from src.value import Value
import src.function as F
import numpy as np

In [2]:
x = Value(np.array([[10, 20], [2, 2]]), "x", requires_grad = True)
w = Value(np.array([0.2, 0.01]), "w", requires_grad = True)
b = Value(np.array([0, 0]), "b", requires_grad = True)
k = F.matmul(x, w)
y = F.add(k, b)
p, sigmoid = F.sigmoid(y, return_func = True)
print(x)
print(w)
print(b)
print(k)
print(y)
print(p)

Creating Function of type <class 'src.function._Matmul'> with name matmul_0
Creating Function of type <class 'src.function._Add'> with name add_0
Creating Function of type <class 'src.function._Sigmoid'> with name sigmoid_0
Value(data=[[10 20]
 [ 2  2]], shape=(2, 2), name=x, requires_grad=True), dtype=int32
Value(data=[0.2  0.01], shape=(2,), name=w, requires_grad=True), dtype=float64
Value(data=[0 0], shape=(2,), name=b, requires_grad=True), dtype=int32
Value(data=[2.2  0.42], shape=(2,), name=x@w, requires_grad=True), dtype=float64
Value(data=[2.2  0.42], shape=(2,), name=(x@w+b), requires_grad=True), dtype=float64
Value(data=[0.90024951 0.60348325], shape=(2,), name=sigma((x@w+b)), requires_grad=True), dtype=float64


In [3]:
sigmoid.backward()

In [4]:
k.function_id

'matmul_0'

In [5]:
y.grad

array([0.08980033, 0.23929122])

In [6]:
x.grad

array([[0.01796007, 0.000898  ],
       [0.04785824, 0.00239291]])

In [7]:
w.grad

array([1.37658572, 2.27458901])

In [8]:
b.grad

array([0.08980033, 0.23929122])

In [5]:
class B(object):
    def __init__(self,):
        super(B, self).__init__()
        
    def f(self, b):
        b._g()
    
    def _g(self, ):
        print("B.g")
        
b = B()
c = B()
b.f(c)

B.g
