In [1]:
from src.value import Value
import src.function as F
import numpy as np

In [2]:
x = Value(np.array([[10, 20], [2, 2]]), "x", requires_grad = True)
w = Value(np.array([0.2, 0.01]), "w", requires_grad = True)
b = Value(np.array([0, 0]), "b", requires_grad = True)
y, linear_f = F.linear(x, w, b, return_func = True)
p, sigmoid = F.sigmoid(y, return_func = True)
x, w, b, y, p

Creating Function of type <class 'src.function._Linear'> with name linear_0
Creating Function of type <class 'src.function._Sigmoid'> with name sigmoid_0


(Value(data=[[10 20]
  [ 2  2]], shape=(2, 2), name=x, requires_grad=True), dtype=int32,
 Value(data=[0.2  0.01], shape=(2,), name=w, requires_grad=True), dtype=float64,
 Value(data=[0 0], shape=(2,), name=b, requires_grad=True), dtype=int32,
 Value(data=[2.2  0.42], shape=(2,), name=(x@w+b), requires_grad=True), dtype=float64,
 Value(data=[0.90024951 0.60348325], shape=(2,), name=sigma((x@w+b)), requires_grad=True), dtype=float64)

In [3]:
sigmoid.backward()

In [4]:
y.grad

array([0.08980033, 0.23929122])

In [5]:
x.grad

0.0203529779779881

In [6]:
w.grad

array([1.37658572, 2.27458901])

In [7]:
b.grad

array([0.08980033, 0.23929122])

In [15]:
A = np.array([[1,0],[0,1]])
B = np.array([1, 1])
A @ B

array([1, 1])

In [ ]:
B.reshape()